//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace versionamento.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projeto()
        {
            this.Repositorio = new HashSet<Repositorio>();
        }
    
        public int Id { get; set; }
        public string Cabecalho { get; set; }
        public string Descricao { get; set; }
        public int IdUnidade { get; set; }
    
        public virtual Unidade Unidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repositorio> Repositorio { get; set; }
    }
}
